[package]
name = "wgpu_dance"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"

winit = "0.30"
wgpu = "24"

futures = "0.3.31"
futures-util = "0.3.31"
tokio = {version = "1.44.2", features = ["rt-multi-thread"]}